export const profileModalContainerStyle = {
    minWidth: "300px",
    width: "650px",
    minHeight: "550px",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    backgroundColor: "#f0f0f0",
    borderRadius: "20px",
    border: "2px solid 03506f",
    display: "flex",
    flexDirection: "column",
    boxShadow: "3px 3px 7px #555, -3px -3px 7px #555",
  };
  
  export const statsModalContainer = {
    maxWidth: "400px",
    minWidth: "300px",
    minHeight: "400px",
    padding: "24px",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    backgroundColor: "#f0f0f0",
    borderRadius: "20px",
    border: "2px solid 03506f",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    boxShadow: "3px 3px 7px #555, -3px -3px 7px #555",
    outline: "none",
  };